name: Deploy Production 

on: 
  workflow_dispatch:
    
jobs: 
  deploy:
    name: Deploy Porduction
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: production
    steps:      
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: |
         npm install -g firebase-tools
         firebase login:ci
         yarn install
      - name: Deploy 
        run: yarn shipit:prod

